# Site settings
title: hiddenbyte_log
email: mehulira@gmail.com
description: > # this means to ignore newlines until "baseurl":
 a blog about sofware development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mehul.pt" # the base hostname & protocol for your site
twitter_username: hiddenbyte
github_username:  hiddenbyte

# Build settings
markdown: kramdown
